Add mizar network policy json conversion
CentaurusInfra/arktos pull request #1090
Opened 2021-05-07 02:31 UTC by clu2xlu

**What type of PR is this?**

Mizar and Arktos Integration for Network Policy feature

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
/kind feature
> /kind flake

**What this PR does / why we need it**:
Mizar network policy communication is through grpc. Mizar is using Python as the programing language and Arktos is using Go. 
In order to have Mizar to read network policy metadata, we need convert Go presentation into a json string and pass it to mizar through GRPC. 
This PR is for json string conversion of the network policy

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

2021-05-11 19:09 UTC, Hong-Chang approved these changes
LGTM

2021-05-11 20:52 UTC, chenqianfzh commented on pkg/controller/mizar/util.go
> +	Rules []MizarNetworkPolicyRule         `json:"to"`
json name is "to", yet the variable nmae is "Rules".

2021-05-11 21:10 UTC, chenqianfzh commented on pkg/controller/mizar/util.go
> +	klog.Infof("Pod Name: %s, HostIP: %s, Namespace: %s, Tenant: %s, Arktos network: %s",
network: %s"

Is network of string type? If not, "%v" is a better formatter.

2021-05-11 21:13 UTC, chenqianfzh commented on pkg/controller/mizar/util.go
> +func parseNetworkPolicySpecToMsg(nps networking.NetworkPolicySpec) MizarNetworkPolicyPolicySpecMsg {
This function can be simplifed as below ( most local variables can be skipped):
{
	return MizarNetworkPolicyPolicySpecMsg{
		PodSel: MizarNetworkPolicyPodSelector{
		     MatchLabels: nps.PodSelector.MatchLabels,
	        }
		In:     parseNetworkPolicyIngressRulesToMsg(nps.Ingress),
		Out:    parseNetworkPolicyEgressRulesToMsg(nps.Egress),
		Type:   policyTypesToStringArray(nps.PolicyTypes),
	}
}

2021-05-12 07:39 UTC, vinaykul commented on pkg/controller/mizar/util.go
> +	klog.Infof("Endpoint Name: %s, Namespace: %s, Tenant: %s, Backend Ips: %s, Ports: %s",
Why did we change the log-level?

2021-05-12 07:40 UTC, vinaykul commented on pkg/controller/mizar/util.go
> +	klog.Infof("Node Name: %s, IP: %s", node.Name, ip)
Same here for log level

2021-05-12 07:52 UTC, vinaykul requested changes
please review the log levels . In order to avoid cluttering up the logs, please keep them at V(3) unless it is unavoidable.

2021-05-13 01:03 UTC, clu2xlu reviewed
In case of 
```
from.PodSelector == nil && from.NamespaceSelector == nil && from.IPBlock == nil 
```
it should return empty. 

```
{"podSelector":{},"policyTypes":["Ingress"]}
```
This test case is already addressed

2021-05-14 08:50 UTC, zmn223 commented
/approve

2021-05-14 08:51 UTC, zmn223 commented
/lgtm

2021-05-14 08:52 UTC, merged